# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import Chat, Optional, ChatsChatIdMessagesGetResponse, ChatMessage, Query

router = APIRouter(tags=['Chats'])


@router.get(
    '/chats', response_model=None, responses={'200': {'model': Chat}}, tags=['Chats']
)
def get_chats() -> Optional[Chat]:
    """
    Получить список чатов текущего пользователя
    """
    pass


@router.post('/chats', response_model=None, tags=['Chats'])
def post_chats(body: Chat = None) -> None:
    """
    Создать чат
    """
    pass


@router.get(
    '/chats/{chat_id}',
    response_model=None,
    responses={'200': {'model': Chat}},
    tags=['Chats'],
)
def get_chats_chat_id(chat_id: int) -> Optional[Chat]:
    """
    Получить чат по идентификатору
    """
    pass


@router.put('/chats/{chat_id}', response_model=None, tags=['Chats'])
def put_chats_chat_id(chat_id: int, body: Chat = None) -> None:
    """
    Редактировать чат
    """
    pass


@router.delete('/chats/{chat_id}', response_model=None, tags=['Chats'])
def delete_chats_chat_id(chat_id: int) -> None:
    """
    Удалить чат
    """
    pass


@router.get(
    '/chats/{chat_id}/messages',
    response_model=None,
    responses={'200': {'model': ChatsChatIdMessagesGetResponse}},
    tags=['Chats'],
)
def get_chats_chat_id_messages(
    chat_id: int,
    last_sequence: Optional[int] = Query(0, alias='lastSequence'),
    count: Optional[int] = 100,
) -> Optional[ChatsChatIdMessagesGetResponse]:
    """
    получить сообщения из чата
    """
    pass


@router.post('/chats/{chat_id}/messages', response_model=None, tags=['Chats'])
def post_chats_chat_id_messages(chat_id: int, body: ChatMessage = None) -> None:
    """
    Отправить сообщение в чат
    """
    pass
