# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import Review, ToursTourIdFeedbackGetResponse, Optional, Ordering

router = APIRouter(tags=['Feedback'])


@router.delete('/feedbacks/{feedback_id}', response_model=None, tags=['Feedback'])
def delete_feedbacks_feedback_id(feedback_id: int) -> None:
    """
    Удалить отзыв
    """
    pass


@router.post(
    '/tours/{tour_id}/feedback', response_model=None, tags=['Feedback', 'Tours']
)
def post_tours_tour_id_feedback(tour_id: int, body: Review = None) -> None:
    """
    Оставить отзыв о туре
    """
    pass


@router.get(
    '/tours/{tour_id}/feedback',
    response_model=None,
    responses={'200': {'model': ToursTourIdFeedbackGetResponse}},
    tags=['Feedback', 'Tours'],
)
def get_tours_tour_id_feedback(
    tour_id: int,
    count: Optional[int] = 50,
    offset: Optional[int] = 0,
    ordering: Optional[Ordering] = 'fresh',
) -> Optional[ToursTourIdFeedbackGetResponse]:
    """
    Получить отзывы о туре
    """
    pass
