# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import Guide, Optional

router = APIRouter(tags=['Guids'])


@router.post('/guids', response_model=None, tags=['Guids'])
def post_guids(body: Guide = None) -> None:
    """
    Создать профиль гида
    """
    pass


@router.get(
    '/guids/{guide_id}',
    response_model=None,
    responses={'200': {'model': Guide}},
    tags=['Guids'],
)
def get_guids_guide_id(guide_id: int) -> Optional[Guide]:
    """
    Получить информацию о гиде
    """
    pass


@router.delete('/guids/{guide_id}', response_model=None, tags=['Guids'])
def delete_guids_guide_id(guide_id: int) -> None:
    """
    удалить профиль гида
    """
    pass


@router.put('/guids/{guide_id}', response_model=None, tags=['Guids'])
def put_guids_guide_id(guide_id: int, body: Guide = None) -> None:
    """
    изменение профиля гида
    """
    pass
