# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import KnowbaseGetResponse, Optional, ToursTourIdNotesGetResponse, Note

router = APIRouter(tags=['Knowledge Base'])


@router.get(
    '/knowbase',
    response_model=None,
    responses={'200': {'model': KnowbaseGetResponse}},
    tags=['Knowledge Base'],
)
def get_knowbase() -> Optional[KnowbaseGetResponse]:
    """
    Получить заметки из базы знаний текущего пользователя
    """
    pass


@router.delete('/knowbase/{note_id}', response_model=None, tags=['Knowledge Base'])
def delete_knowbase_note_id(note_id: int) -> None:
    """
    Удалить заметку
    """
    pass


@router.put('/knowbase/{note_id}', response_model=None, tags=['Knowledge Base'])
def put_knowbase_note_id(note_id: int, body: Note = None) -> None:
    """
    Изменить заметку
    """
    pass


@router.get(
    '/tours/{tour_id}/notes',
    response_model=None,
    responses={'200': {'model': ToursTourIdNotesGetResponse}},
    tags=['Knowledge Base', 'Tours'],
)
def get_tours_tour_id_notes(
    tour_id: int, count: Optional[int] = 50, offset: Optional[int] = 0
) -> Optional[ToursTourIdNotesGetResponse]:
    """
    Получить заметки тура
    """
    pass


@router.post(
    '/tours/{tour_id}/notes', response_model=None, tags=['Knowledge Base', 'Tours']
)
def post_tours_tour_id_notes(tour_id: int, body: Note = None) -> None:
    """
    Добавить заметку к туру
    """
    pass
