# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter
from typing import List, Optional

from ..models import AdminAnalyticsContentGetResponse, AdminAnalyticsSystemGetResponse, AdminAnalyticsUsersGetResponse
from ..models import AdminBackupPostResponse, Backup, AdminBackupRestorePostResponse, AdminBackupRestorePostRequest
from ..models import AdminLogsGetResponseItem, AdminLogsDeleteResponse, AdminUsersUserIdDeleteResponse
from ..models import AdminUsersUserIdPutResponse, User, UserRoleUpdate

router = APIRouter(tags=['Site Management'])


@router.get(
    '/admin/analytics/content',
    response_model=AdminAnalyticsContentGetResponse,
    tags=['Site Management'],
)
def get_admin_analytics_content() -> Optional[AdminAnalyticsContentGetResponse]:
    """
    Просмотр статистики по контенту
    """
    pass


@router.get(
    '/admin/analytics/system',
    response_model=AdminAnalyticsSystemGetResponse,
    tags=['Site Management'],
)
def get_admin_analytics_system() -> Optional[AdminAnalyticsSystemGetResponse]:
    """
    Аналитика работы системы
    """
    pass


@router.get(
    '/admin/analytics/users',
    response_model=AdminAnalyticsUsersGetResponse,
    tags=['Site Management'],
)
def get_admin_analytics_users() -> Optional[AdminAnalyticsUsersGetResponse]:
    """
    Просмотр статистики по пользователям
    """
    pass


@router.post(
    '/admin/backup', response_model=AdminBackupPostResponse, tags=['Site Management']
)
def post_admin_backup() -> Optional[AdminBackupPostResponse]:
    """
    Создание резервной копии
    """
    pass


@router.get('/admin/backup/list', response_model=List[Backup], tags=['Site Management'])
def get_admin_backup_list() -> Optional[List[Backup]]:
    """
    Получение списка резервных копий
    """
    pass


@router.post(
    '/admin/backup/restore',
    response_model=AdminBackupRestorePostResponse,
    tags=['Site Management'],
)
def post_admin_backup_restore(
    body: AdminBackupRestorePostRequest,
) -> Optional[AdminBackupRestorePostResponse]:
    """
    Восстановление данных из резервной копии
    """
    pass


@router.get(
    '/admin/logs',
    response_model=List[AdminLogsGetResponseItem],
    tags=['Site Management'],
)
def get_admin_logs() -> Optional[List[AdminLogsGetResponseItem]]:
    """
    Получение логов системы
    """
    pass


@router.delete(
    '/admin/logs', response_model=AdminLogsDeleteResponse, tags=['Site Management']
)
def delete_admin_logs() -> Optional[AdminLogsDeleteResponse]:
    """
    Очищение логов системы
    """
    pass


@router.get('/admin/users', response_model=List[User], tags=['Site Management'])
def get_admin_users() -> Optional[List[User]]:
    """
    Получение списка пользователей
    """
    pass


@router.get(
    '/admin/users/{user_id}', response_model=List[User], tags=['Site Management']
)
def get_admin_users_user_id(user_id: str) -> Optional[List[User]]:
    """
    Получение информации о пользователе
    """
    pass


@router.delete(
    '/admin/users/{user_id}',
    response_model=AdminUsersUserIdDeleteResponse,
    tags=['Site Management'],
)
def delete_admin_users_user_id(user_id: str) -> Optional[AdminUsersUserIdDeleteResponse]:
    """
    Удаление пользователя
    """
    pass


@router.put(
    '/admin/users/{user_id}',
    response_model=AdminUsersUserIdPutResponse,
    tags=['Site Management'],
)
def put_admin_users_user_id(
    user_id: str, body: UserRoleUpdate = ...
) -> Optional[AdminUsersUserIdPutResponse]:
    """
    Смена роли пользователя
    """
    pass
