# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Tours'])


@router.get(
    '/tours/',
    response_model=None,
    responses={'200': {'model': ToursGetResponse}},
    tags=['Tours'],
)
def get_tours_(
    count: Optional[int] = 50,
    offset: Optional[int] = 0,
    country: Optional[Country] = None,
    city: Optional[City] = None,
    age_limit: Optional[AgeLimit] = Query(None, alias='ageLimit'),
    transport_type: Optional[TourTransportType] = Query(None, alias='transportType'),
    date: Optional[List[str]] = None,
) -> Optional[ToursGetResponse]:
    """
    Получить список туров
    """
    pass


@router.post('/tours/', response_model=None, tags=['Tours'])
def post_tours_(body: Tour = None) -> None:
    """
    Создать тур
    """
    pass


@router.get(
    '/tours/{tour_id}',
    response_model=None,
    responses={'200': {'model': Tour}},
    tags=['Tours'],
)
def get_tours_tour_id(tour_id: int) -> Optional[Tour]:
    """
    Получить информацию о туре
    """
    pass


@router.delete('/tours/{tour_id}', response_model=None, tags=['Tours'])
def delete_tours_tour_id(tour_id: int) -> None:
    """
    Удалить тур
    """
    pass


@router.put('/tours/{tour_id}', response_model=None, tags=['Tours'])
def put_tours_tour_id(tour_id: int, body: Tour = None) -> None:
    """
    Изменить информацию о туре
    """
    pass


@router.get(
    '/tours/{tour_id}/shedule',
    response_model=None,
    responses={'200': {'model': ToursTourIdSheduleGetResponse}},
    tags=['Tours'],
)
def get_tours_tour_id_shedule(tour_id: int) -> Optional[ToursTourIdSheduleGetResponse]:
    """
    Получить расписание тура
    """
    pass


@router.put('/tours/{tour_id}/shedule', response_model=None, tags=['Tours'])
def put_tours_tour_id_shedule(tour_id: int, body: List[SheduleTourDay] = None) -> None:
    """
    Изменить расписание тура
    """
    pass
