# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Users'])


@router.post(
    '/users/login',
    response_model=None,
    responses={'200': {'model': AuthToken}, '401': {'model': ErrorResponse}},
    tags=['Users'],
)
def post_users_login(body: UserLogin) -> Optional[Union[AuthToken, ErrorResponse]]:
    """
    Авторизация пользователя
    """
    pass


@router.get(
    '/users/profile',
    response_model=None,
    responses={'200': {'model': User}, '401': {'model': ErrorResponse}},
    tags=['Users'],
)
def get_users_profile() -> Optional[Union[User, ErrorResponse]]:
    """
    Получить профиль текущего пользователя
    """
    pass


@router.post(
    '/users/register',
    response_model=None,
    responses={'400': {'model': ErrorResponse}},
    tags=['Users'],
)
def post_users_register(body: UserRegistration) -> Optional[ErrorResponse]:
    """
    Регистрация нового пользователя
    """
    pass
