# generated by fastapi-codegen:
#   filename:  D:\VSU\OpenTour\docs\api\OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from datetime import date as date_aliased
from datetime import datetime, time
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field, SecretStr, RootModel


class UserLogin(BaseModel):
    email: EmailStr
    password: SecretStr


class UserRegistration(UserLogin):
    username: str


class UserRole(Enum):
    guide = 'guide'
    admin = 'admin'
    participant = 'participant'


class User(BaseModel):
    userID: int = Field(description='Сквозной идентификатор пользователя', examples=['123'])
    userName: str = Field(description='Имя пользователя', examples=['john doe'])
    about: Optional[str] = Field(None, description='Раздел о себе')
    userRoles: List[UserRole] = Field(description='Роли участника')
    regDate: datetime = Field(description='Время регистрации пользователя')


class AuthToken(BaseModel):
    access_token: Optional[str] = Field(None, description='JWT токен для авторизации')


class ErrorResponse(BaseModel):
    error: Optional[str] = Field(None, description='Сообщение об ошибке')


class Booking(BaseModel):
    bookingID: Optional[int] = None
    userID: Optional[int] = Field(
        None, description='Идентификатор пользователя, осуществляющего бронирование'
    )
    tourID: Optional[int] = None
    sessionID: Optional[int] = None
    tariffID: Optional[int] = None


class AgeLimit(Enum):
    integer_0 = 0
    integer_6 = 6
    integer_12 = 12
    integer_16 = 16
    integer_18 = 18


class Language(Enum):
    Russian = 'Русский'
    English = 'English'


class Currency(Enum):
    RUB = 'RUB'
    USD = 'USD'


class TourTransportType(Enum):
    walking = 'walking'
    scooter = 'scooter'
    bus = 'bus'


class SheduleTourSession(BaseModel):
    sessionID: int
    startTime: time
    endTime: time
    availavbleTariffs: List[int] = Field(
        description='Список идентификаторов доступных тарифов'
    )


class Status(Enum):
    created = 'created'
    restoring = 'restoring'
    failed = 'failed'


class Backup(BaseModel):
    backupID: str = Field(
        description='Идентификатор резервной копии', examples=['backup_12345']
    )
    createTime: datetime = Field(
        description='Время создания резервной копии',
        examples=['2025-03-03T12:00:00Z'],
    )
    status: Status = Field(description='Статус резервной копии', examples=['created'])


class NewRole(Enum):
    guide = 'guide'
    admin = 'admin'
    participant = 'participant'


class UserRoleUpdate(BaseModel):
    newRole: NewRole = Field(description='Новая роль пользователя', examples=['guide'])


class City(Enum):
    Voronezh = 'Воронеж'
    Moscow = 'Москва'
    Saint_Petersburg = 'Санкт-Петербург'


class Country(Enum):
    Russia = 'Россия'


class UserRole1(Enum):
    participant = 'participant'
    guide = 'guide'
    admin = 'admin'


class Review(BaseModel):
    reviewID: int = Field(description='Идентификатор отзыва')
    authorID: int = Field(description='Идентификатор пользователя, оставившего отзыв')
    reviewTitle: Optional[str] = Field(None, description='Заголовок отзыва')
    reviewText: Optional[str] = Field(None, description='Текст отзыва')
    reviewScore: float = Field(description='Оценка')
    upvotes: Optional[int] = Field(
        None, description='Количество положительных отметок отзыва'
    )
    downvotes: Optional[int] = Field(
        None, description='количество отрицательных оценок отзыва'
    )
    createdAt: datetime
    updatedAt: Optional[datetime] = None


class ReviewComment(BaseModel):
    commentID: int
    authorID: int
    reviewID: int
    commentText: str
    createdAt: datetime


class Timeframe(BaseModel):
    startTime: datetime = Field(description='Время начала')
    endTime: Optional[datetime] = Field(None, description='Время окончания')
    isPoint: Optional[str] = Field(
        None,
        description='Если отсутствует время окончания и `isPoint=true`, временной отрезок считается точкой',
    )


class Chat(BaseModel):
    chatID: int
    chatName: str
    members: List[User]


class Message(BaseModel):
    messageID: int = Field(description='Идентификатор сообщения')
    authorID: int = Field(description='Идентификатор автора сообщения')
    text: str = Field(description='Текстовое содержимое сообщения')
    sequence: int = Field(description='Порядковый номер сообщения в чате')
    createAt: datetime
    updateAt: Optional[datetime] = None


class ChatMessage(Message):
    chatID: int = Field(description='Идентификатор чата')


class PrivateMessage(Message):
    recipientID: Optional[int] = Field(None, description='Идентификатор получателя')


class ChatsChatIdMessagesGetResponse(RootModel):
    root: List[ChatMessage]


class Ordering(Enum):
    scoreAsc = 'scoreAsc'
    scoreDesc = 'scoreDesc'
    fresh = 'fresh'
    old = 'old'


class ToursTourIdFeedbackGetResponse(RootModel):
    root: List[Review]


class AdminUsersUserIdDeleteResponse(BaseModel):
    message: str = Field(examples=['Пользователь user_12345 успешно удален'])


class AdminUsersUserIdPutResponse(BaseModel):
    message: str = Field(examples=['Роль пользователя user_12345 изменена на guide'])


class Level(Enum):
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'
    DEBUG = 'DEBUG'
    FATAL = 'FATAL'


class AdminLogsGetResponseItem(BaseModel):
    timeStamp: datetime = Field(
        description='Время события', examples=['2025-03-03T12:00:00Z']
    )
    level: Level = Field(description='Уровень важности лога', examples=['INFO'])
    message: str = Field(
        description='Сообщение лога',
        examples=['Пользователь успешно вошел в систему'],
    )
    user_id: str = Field(
        description='Идентификатор пользователя, вызвавшего событие',
        examples=['user_12345'],
    )


class AdminLogsDeleteResponse(BaseModel):
    message: str = Field(examples=['Логи успешно очищены'])


class AdminBackupPostResponse(BaseModel):
    message: str = Field(examples=['Резервная копия успешно создана'])


class AdminBackupRestorePostRequest(BaseModel):
    backupID: str = Field(
        description='Идентификатор резервной копии для восстановления',
        examples=['backup_12345'],
    )


class AdminBackupRestorePostResponse(BaseModel):
    message: str = Field(
        examples=['Данные успешно восстановлены из резервной копии backup_12345']
    )


class AdminAnalyticsUsersGetResponse(BaseModel):
    totalUsers: int = Field(
        description='Общее количество пользователей', examples=['1500']
    )
    activeUsers: int = Field(
        description='Количество активных пользователей', examples=['1000']
    )
    inactiveUsers: int = Field(
        description='Количество неактивных пользователей', examples=['500']
    )


class AdminAnalyticsContentGetResponse(BaseModel):
    totalNotes: int = Field(description='Общее количество заметок', examples=['200'])
    totalTours: int = Field(description='Общее количество экскурсий', examples=['50'])
    contentInteraction: int = Field(
        description='Общее количество взаимодействий с контентом (просмотры, лайки, комментарии и т.д.)',
        examples=[10000],
    )


class AdminAnalyticsSystemGetResponse(BaseModel):
    errorsLast24h: int = Field(
        description='Количество ошибок за последние 24 часа', examples=['5']
    )
    totalRequests: int = Field(
        description='Общее количество запросов к системе', examples=['100000']
    )


class Guide(User):
    availableLanguages: Optional[List[Language]] = Field(
        None, description='Языки которыми владеет экскурсовод'
    )
    guideRating: Optional[float] = Field(None, description='рейтинг экскурсовода')
    guideNumberOfTour: Optional[int] = Field(
        None, description='количество проведенных экскурсий'
    )
    guidePhotoProfile: Optional[str] = Field(
        None, description='Аватарка на профиле гида'
    )
    guidePhotos: Optional[List[str]] = Field(
        None, description='остальные фото в профиле'
    )


class Cost(BaseModel):
    numCost: float = Field(description='Цена в целых единицах валюты')
    currency: Currency


class SheduleTourDay(BaseModel):
    date: date_aliased
    availableSessions: List[SheduleTourSession]


class Note(BaseModel):
    noteID: int = Field(description='Идентификатор заметки')
    authorID: int = Field(description='Идентификатор автора заметки')
    noteTitle: str = Field(description='Заголовок заметки')
    noteText: str = Field(description='Текст заметки')
    createdAt: datetime = Field(description='Время создания заметки')
    updatedAt: Optional[datetime] = Field(None, description='Время изменения заметки')
    timeframe: Optional[Timeframe] = None
    tourID: Optional[int] = Field(None, description='Связанная экскурсия')


class ToursTourIdSheduleGetResponse(RootModel):
    root: List[SheduleTourDay] = Field(
        description='Список дней с указанием статуса'
    )


class ToursTourIdShedulePutRequest(RootModel):
    root: List[SheduleTourDay] = Field(
        description='Список дней с указанием статуса'
    )


class ToursTourIdNotesGetResponse(RootModel):
    root: List[Note]


class KnowbaseGetResponse(RootModel):
    root: List[Note]


class Tariff(BaseModel):
    tariffID: Optional[int] = Field(None, description='Идентификатор тарифа')
    cost: Cost
    minGroupSize: int = Field(description='Минимальный размер группы')
    maxGroupSize: int = Field(
        description='Максимальный размер экскурсионной группы'
    )
    costsDescription: Optional[str] = Field(
        None, description='Описание услуг (что входит в цену)'
    )
    extraCosts: Optional[str] = Field(
        None, description='Описание дополнительных расходов'
    )
    isPersonal: Optional[str] = Field(
        None, description='Флаг персонального тарифа - группа только ваша'
    )


class Tour(BaseModel):
    tourID: int
    tourName: str
    tourSummary: str = Field(description='Краткое описание экскурсии')
    tourDescription: Optional[str] = Field(
        None, description='Полное описание экскурсии'
    )
    duration: int = Field(description='Длительность экскурсии (в минутах)')
    hardwareRequirements: Optional[str] = Field(
        None, description='Требования к оборудованию (в виде текстового описания)'
    )
    safetyRequirements: Optional[str] = Field(
        None, description='Требования по безопасности (в виде текстового описания)'
    )
    healthRestrictions: Optional[str] = Field(
        None, description='Ограничения по здоровью (в виде текстового описания)'
    )
    ageLimit: AgeLimit
    availableLanguages: List[Language] = Field(
        description='Список поддерживаемых языков'
    )
    costs: List[Tariff] = Field(description='Тарифы на экскурсионные группы')
    transportType: TourTransportType
    photos: Optional[List[str]] = None


class ToursGetResponse(RootModel):
    root: List[Tour]
