# generated by fastapi-codegen:
#   filename:  OpenTour_api_v1.0.yaml
#   timestamp: 2025-04-28T18:32:34+00:00

from fastapi import FastAPI
import uvicorn
import os

from api.routers import (
    chats,
    feedback,
    guids,
    knowledge_base,
    site_management,
    tours,
    users,
)

app = FastAPI(
    title='OpenTour',
    version='v1.0'
)

app.include_router(chats.router)
app.include_router(feedback.router)
app.include_router(guids.router)
app.include_router(knowledge_base.router)
app.include_router(site_management.router)
app.include_router(tours.router)
app.include_router(users.router)


HOST = os.environ.get('PORT', 8000)
PORT = os.environ.get('HOST', "localhost")

@app.get("/")
async def root():
    return {"is_working": True}


if __name__ == "__main__":
    uvicorn.run(
        "main:app", 
        reload=True, 
        host=HOST, 
        port=PORT
        )