openapi: 3.0.3
info:
  title: OpenTour
  version: v1.0



tags:
  - name: Users
    description: Работа с профилями участников
  - name: Tours 
    description: Работа с турами
  - name: Guids
    description: Работа с профилями гидов
  - name: Chats
    description: Работа с чатами
  - name: Feedback
    description: Работа с отзывами
  - name: Knowledge Base 
    description: Работа с базой знаний (заметки)
  - name: Site Management
    description: Административные функции



paths:
  /tours/:
    get: 
      summary: Получить список туров
      tags:
        - Tours 
      parameters:
        - name: count 
          in: query
          required: false 
          description: 
            Число туров в списке
          schema: 
            type: integer
            default: 50
        - name: offset
          in: query
          required: false
          description: 
            Сдвиг от начала списка (для постраничной выборки)
          schema: 
            type: integer
            default: 0 
        - name: country 
          in: query
          required: false
          schema: 
            $ref: '#/components/schemas/Country'
        - name: city
          in: query
          required: false
          schema: 
            $ref: '#/components/schemas/City'
        - name: ageLimit
          in: query
          required: false
          schema: 
            $ref: '#/components/schemas/AgeLimit'
        - name: transportType
          in: query
          required: false
          schema: 
            $ref: '#/components/schemas/TourTransportType'
        - name: date
          in: query
          required: false
          schema: 
            type: array
            items: 
              type: string 
              format: date
      responses:
        200: 
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Tour'
    post: 
      summary: Создать тур
      tags: 
        - Tours
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Tour'
      responses: 
        201: 
          description: Усепешно создано

  /tours/{tour_id}:
    get:
      summary: Получить информацию о туре
      tags: 
        - Tours
      parameters:
        - name: tour_id
          in: path
          required: true 
          schema: 
            type: integer
      responses: 
        200: 
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Tour'
        404: 
          description: Не найдено
    delete:
      summary: Удалить тур 
      tags: 
        - Tours
      parameters:
        - name: tour_id
          in: path
          required: true 
          schema: 
            type: integer
      responses: 
        200: 
          description: OK
    put: 
      summary: Изменить информацию о туре
      tags: 
        - Tours
      parameters:
        - name: tour_id
          in: path
          required: true 
          schema: 
            type: integer
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Tour'
      responses: 
        200: 
          description: OK

  /tours/{tour_id}/shedule: 
    get: 
      summary: Получить расписание тура
      tags: 
        - Tours
      parameters:
        - name: tour_id
          in: path
          required: true 
          schema: 
            type: integer
      responses: 
        200: 
          description: OK
          content:
            application/json:
              schema: 
                type: array
                description: 
                  Список дней с указанием статуса
                items:
                  $ref: '#/components/schemas/TourDay'
    put: 
      summary: Изменить расписание тура
      tags: 
        - Tours
      parameters:
        - name: tour_id
          in: path
          required: true 
          schema: 
            type: integer
      requestBody: 
        content:
            application/json:
              schema: 
                type: array
                description: 
                  Список дней с указанием статуса
                items:
                  $ref: '#/components/schemas/TourDay'
      responses: 
        200: 
          description: OK
          
  /guids/{guide_id}:
    get:
      summary: Получить информацию о гиде
      tags:
        - Guids
      parameters:
        - name: guide_id 
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guide'
        404:
            description: Не найдено   

    delete:
      summary: удалить профиль гида
      tags:
        - Guids
      parameters:
        - name: guide_id 
          in: path
          required: true
          schema:
            type: integer       
      responses:
        200:
          description: OK
        404:
            description: Не найдено   

    post:
      summary: Создать профиль гида
      tags: 
        - Guids
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guide'
      responses:
        201:        
          description: Успешно созданно   
        400:
          description: Ошибка в запросе
          
    put:
      summary: изменение профиля гида
      tags: 
        - Guids
      parameters:
          - name: guide_id 
            in: path
            required: true
            schema:
              type: integer
      requestBody:
        content:
          application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Guide'
      responses:          
        200:
          description: OK        
        404:
          description: Не найдено  

components:
  schemas:
    User:
      type: object
      description: Пользователь системы
    
    Guide:
      type: object
      description: Профиль экскурсовода
      required:
        - guideID
        - guideName
      properties:
        guideID:
          type: integer
          readOnly: true
        guideName:
          type: string
        availableLanguages:
          type: array
          items: 
            $ref: '#/components/schemas/Language'
          description: 
            Языки которыми владеет экскурсовод
        guideRating:
          readOnly: true
          type: number
          description: 
            рейтинг экскурсовода
        guideNumberOfTour:
          readOnly: true
          type: integer
          description: 
            количество проведенных экскурсий
        guidePhotoProfile:
          type: string
          description: 
            Аватарка на профиле гида
        guidePhoto: 
          type: array
          items: 
            type: string
          description: остальные фото в профиле


    Tour: 
      type: object
      description: 
        Экскурсия
      required:
        - tourID 
        - tourName 
        - tourSummary 
        - duration 
        - ageLimit 
        - availableLanguages 
        - costs 
        - shedule 
        - transportType 
      properties: 
        tourID: 
          type: integer
          readOnly: true
        tourName:
          type: string
        tourSummary: 
          type: string
          description: 
            Краткое описание экскурсии
        tourDescription:
          type: string
          description: 
            Полное описание экскурсии
        duration:
          type: integer
          description: 
            Длительность экскурсии (в минутах)
        hardwareRequirements: 
          type: string
          description: 
            Требования к оборудованию (в виде текстового описания)
        safetyRequirements: 
          type: string
          description: 
            Требования по безопасности (в виде текстового описания)
        healthRestrictions: 
          type: string 
          description: 
            Ограничения по здоровью (в виде текстового описания)
        ageLimit: 
          $ref: '#/components/schemas/AgeLimit'
        availableLanguages:
          type: array
          description: 
            Список поддерживаемых языков
          items: 
            $ref: '#/components/schemas/Language'
        costs: 
          type: array
          description: 
            Тарифы на экскурсионные группы
          items:
            $ref: '#/components/schemas/GroupSizeCosts'
        transportType: 
          $ref: '#/components/schemas/TourTransportType'
        photos: 
          type: array
          items: 
            type: string
            example: https://opentest.info/photo.jpg
        
    AgeLimit: 
      type: integer
      description: 
        Возрастное ограничение (минимальный возраст)
      enum: 
        - 0
        - 6
        - 12
        - 16
        - 18

    Language: 
      type: string 
      description: 
        Язык
      enum: 
        - Русский
        - English

    GroupSizeCosts:
      type: object
      description: 
        Цена экскурсии для указанного размера группы
      required:
        - cost 
        - minGroupSize 
        - maxGroupSize 
      properties:
        cost: 
          $ref: '#/components/schemas/Cost'
        minGroupSize: 
          type: integer
          description: 
            Минимальный размер группы
        maxGroupSize: 
          type: integer 
          description: 
            Максимальный размер экскурсионной группы
        costsDescription: 
          type: string 
          description: 
            Описание услуг (что входит в цену)
        extraCosts: 
          type: string
          description: 
            Описание дополнительных расходов 

    Cost: 
      type: object
      description: 
        Цена
      required:
        - numCost 
        - currency
      properties:
        numCost: 
          type: number
          description: 
            Цена в целых единицах валюты
        currency: 
          $ref: '#/components/schemas/Currency'

    Currency:
      type: string 
      description: 
        Наименование валюты
      enum:
        - RUB
        - USD

    TourTransportType: 
      type: string
      description: 
        Тип транспорта
      enum: 
        - walking
        - scooter
        - bus

    TourDayStatus: 
      type: string 
      description: 
        Статус экскурсионного дня
      enum:
        - free
        - occupied

    TourDay: 
      type: object
      description: 
        Экскурсионный день
      required:
        - date 
        - status
      properties:
        date: 
          type: string 
          format: date 
        status: 
          $ref: '#/components/schemas/TourDayStatus'

    City: 
      type: string 
      enum:
        - Воронеж
        - Москва
        - Санкт-Петербург

    Country: 
      type: string 
      enum:
        - Россия
