name: lint-test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install mypy ruff

      - name: Run ruff lint
        run: ruff check

      - name: Run mypy lint
        run: mypy --install-types --non-interactive ./app

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install pytest

      - name: Run pytest to test code
        run: pytest -v -s tests/

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secret.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=staging-{{sha}}-{{date 'YYYYMMDDHHmmss'}},enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Default tag if not in metadata action
        id: set_tag
        run: |
          if [ -z "${{ steps.meta.output.tags }}" ]; then
            TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:temp-${GITHUB_SHA:8}-$(date +%s)"
          else
            TAG="${{ steps.meta.outputs.tags }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT


      - name: Build and push to docker registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: "${{ steps.set_tag.outputs.tag }}"